pub mod entropy;
pub mod codec;

use entropy::FastAdaptiveModel;
use codec::{FastRangeEncoder, FastRangeDecoder};

/// Compresses a given byte array.
/// Returns a dynamically sized vector containing a 4-byte header (original length)
/// followed by the encoded arithmetic payload.
pub fn compress(input: &[u8]) -> Vec<u8> {
    let mut model = FastAdaptiveModel::new();
    let mut enc = FastRangeEncoder::with_capacity(input.len() / 2 + 16);

    for &byte in input {
        enc.encode(byte, &mut model);
    }

    let mut output = Vec::with_capacity(4 + enc.output().len() + 8);
    // Store the original length as a 4-byte little-endian integer
    output.extend_from_slice(&(input.len() as u32).to_le_bytes());
    output.extend_from_slice(enc.finish());

    output
}

/// Decompresses a payload previously generated by the `compress` function.
/// Returns None if the input is malformed or too short.
pub fn decompress(data: &[u8]) -> Option<Vec<u8>> {
    if data.len() < 4 {
        return None;
    }

    // Extract the original length from the first 4 bytes
    let orig_len = u32::from_le_bytes([data[0], data[1], data[2], data[3]]) as usize;
    let payload = &data[4..];

    let mut model = FastAdaptiveModel::new();
    let mut dec = FastRangeDecoder::new(payload)?;
    let mut result = Vec::with_capacity(orig_len);

    for _ in 0..orig_len {
        let sym = dec.decode(&mut model);
        result.push(sym);
    }

    Some(result)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_roundtrip_text() {
        let text = b"AXIOMA ultimate universal compressor - zero allocations test payload";
        let comp = compress(text);
        let decomp = decompress(&comp).expect("Decompression failed");
        assert_eq!(text.to_vec(), decomp, "Text payload mismatch after decompression");
    }

    #[test]
    fn test_roundtrip_random() {
        let mut data = vec![0u8; 64_000];
        // Generate pseudo-random deterministic data
        for (i, byte) in data.iter_mut().enumerate() {
            *byte = ((i * 1103515245 + 12345) >> 16) as u8;
        }
        let comp = compress(&data);
        let decomp = decompress(&comp).expect("Decompression failed");
        assert_eq!(data, decomp, "Random payload mismatch after decompression");
    }
}
